spring:
  main:
    web-application-type: none
  profiles:
    default: local
---

spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    rest:
      uris: "http://172.31.43.38:9200"
