version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/2021-findcvs/api
hooks:
  BeforeInstall:
    - location: scripts/02_before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/04_after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/05_application_start.sh
      timeout: 3600
      runas: root

permissions:
  - object: /2021_hoseo_findcvs/api
    pattern: "*"
    owner: ec2-user
    group: ec2-user
    mode: 755

